import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Container from "@/components/Container";
import { UserProvider } from "./(context)/UserContext";
import { Toaster } from "@/components/ui/sonner";
// import { SessionProvider } from "next-auth/react";
// import { Providers } from "./Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-950 text-white overflow-y-scroll`}
      >
        {/* <Providers> */}

        <UserProvider>
          <Toaster />
          <Container>
            <Header></Header>
            {children}
            <Footer></Footer>
          </Container>
        </UserProvider>
        {/* </Providers> */}
      </body>
    </html>
  );
}
